name: Trigger VPS Deployment

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Trigger VPS Playbook Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          # token: ${{ secrets.PAT }}
          repository: dmitriaronson/vps-playbook
          event-type: deploy-dmitriaronsoncom
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
